### ISSUE TITLE
Erorrs upon installation

### ISSUE THREAD

**Issue by File14** [KazeJiyu/eclipse-discord-integration#37]
Hello,

I tried to install this plugin on Eclipse IDE Photon Milestone 6 but ran into a few errors. I hope you can fix them.

```
`
!ENTRY org.eclipse.equinox.p2.core 4 0 2018-06-10 21:54:19.996
!MESSAGE Provisioning exception
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: No repository found at http://ftp-stud.fht-esslingen.de/pub/Mirrors/eclipse/mpc/releases/1.4.2/mpc-1.4.2.zip.
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:395)
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:117)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.fail(CachingRepositoryManager.java:353)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:244)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:476)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:102)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.doLoad(LoadMetadataRepositoryJob.java:118)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.runModal(LoadMetadataRepositoryJob.java:103)
	at org.eclipse.equinox.internal.p2.ui.sdk.PreloadingRepositoryHandler$1.runModal(PreloadingRepositoryHandler.java:81)
	at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
!SUBENTRY 1 org.eclipse.equinox.p2.metadata.repository 4 1000 2018-06-10 21:54:19.996
!MESSAGE No repository found at http://ftp-stud.fht-esslingen.de/pub/Mirrors/eclipse/mpc/releases/1.4.2/mpc-1.4.2.zip.

!ENTRY org.eclipse.equinox.p2.core 4 0 2018-06-10 21:54:20.017
!MESSAGE Provisioning exception
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: No repository found at jar:file:/C:/Users/Desktop/mpc-1.4.2.zip!/.
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:395)
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:117)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.fail(CachingRepositoryManager.java:353)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:244)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:476)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:102)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.doLoad(LoadMetadataRepositoryJob.java:118)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.runModal(LoadMetadataRepositoryJob.java:103)
	at org.eclipse.equinox.internal.p2.ui.sdk.PreloadingRepositoryHandler$1.runModal(PreloadingRepositoryHandler.java:81)
	at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
!SUBENTRY 1 org.eclipse.equinox.p2.metadata.repository 4 1000 2018-06-10 21:54:20.017
!MESSAGE No repository found at jar:file:/C:/Users/Desktop/mpc-1.4.2.zip!/.

!ENTRY org.eclipse.equinox.p2.core 4 0 2018-06-10 21:54:22.659
!MESSAGE Provisioning exception
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: No repository found at http://www.eclipse.org/downloads/download.php?file=/mpc/releases/1.4.2/mpc-1.4.2.zip&mirror_id=1.
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:395)
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:117)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.fail(CachingRepositoryManager.java:353)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:244)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:476)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:102)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.doLoad(LoadMetadataRepositoryJob.java:118)
	at org.eclipse.equinox.p2.ui.LoadMetadataRepositoryJob.runModal(LoadMetadataRepositoryJob.java:103)
	at org.eclipse.equinox.internal.p2.ui.sdk.PreloadingRepositoryHandler$1.runModal(PreloadingRepositoryHandler.java:81)
	at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
!SUBENTRY 1 org.eclipse.equinox.p2.metadata.repository 4 1000 2018-06-10 21:54:22.659
!MESSAGE No repository found at http://www.eclipse.org/downloads/download.php?file=/mpc/releases/1.4.2/mpc-1.4.2.zip&mirror_id=1.

!ENTRY org.eclipse.equinox.p2.ui 4 0 2018-06-10 21:55:20.069
!MESSAGE No such member: attributes
!STACK 0
java.lang.IllegalArgumentException: No such member: attributes
	at org.eclipse.equinox.internal.p2.metadata.ProvidedCapability.getMember(ProvidedCapability.java:154)
	at org.eclipse.equinox.internal.p2.metadata.expression.Member$DynamicMember.invoke(Member.java:48)
	at org.eclipse.equinox.internal.p2.metadata.expression.Member$DynamicMember.evaluate(Member.java:43)
	at org.eclipse.equinox.internal.p2.metadata.expression.Matches.evaluate(Matches.java:37)
	at org.eclipse.equinox.internal.p2.metadata.expression.And.evaluate(And.java:27)
	at org.eclipse.equinox.internal.p2.metadata.expression.Unary.evaluate(Unary.java:46)
	at org.eclipse.equinox.internal.p2.metadata.expression.Exists.evaluate(Exists.java:30)
	at org.eclipse.equinox.internal.p2.metadata.expression.CollectionFilter.evaluate(CollectionFilter.java:62)
	at org.eclipse.equinox.internal.p2.metadata.expression.MatchExpression.evaluate(MatchExpression.java:48)
	at org.eclipse.equinox.p2.query.ExpressionMatchQuery.isMatch(ExpressionMatchQuery.java:100)
	at org.eclipse.equinox.p2.query.ExpressionMatchQuery.perform(ExpressionMatchQuery.java:86)
	at org.eclipse.equinox.p2.query.ExpressionMatchQuery.perform(ExpressionMatchQuery.java:75)
	at org.eclipse.equinox.internal.p2.metadata.index.IndexProvider.query(IndexProvider.java:23)
	at org.eclipse.equinox.internal.p2.metadata.index.IndexProvider.query(IndexProvider.java:33)
	at org.eclipse.equinox.internal.p2.director.Slicer.expandRequirement(Slicer.java:183)
	at org.eclipse.equinox.internal.p2.director.Slicer.processIU(Slicer.java:146)
	at org.eclipse.equinox.internal.p2.director.Slicer.slice(Slicer.java:65)
	at org.eclipse.equinox.internal.p2.director.SimplePlanner.getSolutionFor(SimplePlanner.java:332)
	at org.eclipse.equinox.internal.p2.director.SimplePlanner.getProvisioningPlan(SimplePlanner.java:389)
	at org.eclipse.equinox.internal.p2.operations.PlannerResolutionJob.runModal(PlannerResolutionJob.java:77)
	at org.eclipse.equinox.p2.operations.ProfileChangeOperation.resolveModal(ProfileChangeOperation.java:115)
	at org.eclipse.equinox.internal.p2.ui.dialogs.ProvisioningOperationWizard.lambda$1(ProvisioningOperationWizard.java:275)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

!ENTRY org.eclipse.equinox.p2.ui 4 0 2018-06-10 21:55:20.073
!MESSAGE Unexpected error

!ENTRY org.eclipse.equinox.p2.operations 4 0 2018-06-10 21:55:20.076
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.operations 4 10001 2018-06-10 21:55:20.076
!MESSAGE Your original request has been modified.
!SUBENTRY 2 org.eclipse.equinox.p2.operations 4 0 2018-06-10 21:55:20.076
!MESSAGE Unexpected Error.  Could not process the request. Check the error log for details.

!ENTRY org.eclipse.equinox.p2.operations 4 0 2018-06-10 21:55:20.084
!MESSAGE Operation details
!SUBENTRY 1 org.eclipse.equinox.p2.operations 4 10001 2018-06-10 21:55:20.084
!MESSAGE Your original request has been modified.
!SUBENTRY 2 org.eclipse.equinox.p2.operations 4 0 2018-06-10 21:55:20.084
!MESSAGE Unexpected Error.  Could not process the request. Check the error log for details.
`
```

**Comment by File14** [comment]
Reinstalled Eclipse and it now worked.
